// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ysfzevlqklmtnhmvoziz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlzZnpldmxxa2xtdG5obXZveml6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwMjcyODcsImV4cCI6MjA2ODYwMzI4N30.KF7nyWag6CBIBM2MnpTVM0Y3hmE598kCPi_AMaHjaJI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});